name: generate animation

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - snk

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snk.svg
            assets/snk-dark.svg?palette=github-dark

      - name: push snk.svg to the snk branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snk
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
