name: Update README

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Run update script
        run: python update.py

      - name: Remove existing snake animation
        run: rm -f assets/snk.svg assets/snk-dark.svg

      - name: Generate new snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snk.svg
            assets/snk-dark.svg?palette=github-dark

      - name: Commit and push changes
        run: |
          git config --global user.name 'MeewMeew'
          git config --global user.email 'mauminh.nguyen@gmail.com'
          git add .
          git commit -m "Auto-update README.md"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
